t = int(input('Tabuada do número:'))
n0 = t*0
n1 = t*1
n2 = t*2
n3 = t*3
n4 = t*4
n5 = t*5
n6 = t*6
n7 = t*7
n8 = t*8
n9 = t*9
n10 = t*10
print('{}x0= {}'.format(t, n0))
print('{}x1= {}'.format(t, n1))
print('{}x2= {}'.format(t ,n2))
print('{}x3= {}'.format(t, n3))
print('{}x4= {}'.format(t, n4))
print('{}x5= {}'.format(t, n5))
print('{}x6= {}'.format(t, n6))
print('{}x7= {}'.format(t, n7))
print('{}x8= {}'.format(t, n8))
print('{}x9= {}'.format(t, n9))
print('{}x10= {}'.format(t,n10))